steps:
  # install dependencies
  - name: python:3.8-slim
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  # run in python 3.8 which is latest version in Cloud Composer
  - name: python:3.8-slim
    entrypoint: python3.8
    args: [ "-m", "pytest", "-s", "dags/" ]
    options:
      logging: CLOUD_LOGGING_ONLY  # Ensure logging is configured as required